exclude: "\\.patch$"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: mixed-line-ending
  - repo: https://github.com/kamadorueda/alejandra
    rev: 4.0.0
    hooks:
      - id: alejandra-system
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.8.0-1
    hooks:
      - id: shfmt
        args: [--write, --simplify, --indent=4, --case-indent, --space-redirects]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.11
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-check
        args: [--select, I, --fix]
      - id: ruff-format
        args: [--line-length, "100"]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
        args: [--skip=*.nix]
